//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SortProxy.SortService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfBase64Binary", Namespace="http://localhost/SortService.asmx/", ItemName="base64Binary")]
    [System.SerializableAttribute()]
    public class ArrayOfBase64Binary : System.Collections.Generic.List<byte[]> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/SortService.asmx/", ConfigurationName="SortService.SortServiceSoap")]
    public interface SortServiceSoap {
        
        // CODEGEN: Generating message contract since element name matrix from namespace http://localhost/SortService.asmx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/SortService.asmx/SortMatrix", ReplyAction="*")]
        SortProxy.SortService.SortMatrixResponse SortMatrix(SortProxy.SortService.SortMatrixRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SortMatrixRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SortMatrix", Namespace="http://localhost/SortService.asmx/", Order=0)]
        public SortProxy.SortService.SortMatrixRequestBody Body;
        
        public SortMatrixRequest() {
        }
        
        public SortMatrixRequest(SortProxy.SortService.SortMatrixRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/SortService.asmx/")]
    public partial class SortMatrixRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SortProxy.SortService.ArrayOfBase64Binary matrix;
        
        public SortMatrixRequestBody() {
        }
        
        public SortMatrixRequestBody(SortProxy.SortService.ArrayOfBase64Binary matrix) {
            this.matrix = matrix;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SortMatrixResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SortMatrixResponse", Namespace="http://localhost/SortService.asmx/", Order=0)]
        public SortProxy.SortService.SortMatrixResponseBody Body;
        
        public SortMatrixResponse() {
        }
        
        public SortMatrixResponse(SortProxy.SortService.SortMatrixResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/SortService.asmx/")]
    public partial class SortMatrixResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SortProxy.SortService.ArrayOfBase64Binary matrix;
        
        public SortMatrixResponseBody() {
        }
        
        public SortMatrixResponseBody(SortProxy.SortService.ArrayOfBase64Binary matrix) {
            this.matrix = matrix;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SortServiceSoapChannel : SortProxy.SortService.SortServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SortServiceSoapClient : System.ServiceModel.ClientBase<SortProxy.SortService.SortServiceSoap>, SortProxy.SortService.SortServiceSoap {
        
        public SortServiceSoapClient() {
        }
        
        public SortServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SortServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SortServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SortServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SortProxy.SortService.SortMatrixResponse SortProxy.SortService.SortServiceSoap.SortMatrix(SortProxy.SortService.SortMatrixRequest request) {
            return base.Channel.SortMatrix(request);
        }
        
        public void SortMatrix(ref SortProxy.SortService.ArrayOfBase64Binary matrix) {
            SortProxy.SortService.SortMatrixRequest inValue = new SortProxy.SortService.SortMatrixRequest();
            inValue.Body = new SortProxy.SortService.SortMatrixRequestBody();
            inValue.Body.matrix = matrix;
            SortProxy.SortService.SortMatrixResponse retVal = ((SortProxy.SortService.SortServiceSoap)(this)).SortMatrix(inValue);
            matrix = retVal.Body.matrix;
        }
    }
}
