function Hd = lowpass( Fsamp )
%LOWPASS Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.11 and the Signal Processing Toolbox 6.14.
%
% Generated on: 06-May-2011 20:20:58
%

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
if nargin < 1       % If there is no input arguments
    Fsamp = 44100;  % Sampling Frequency
end

Fpass = 502;         % Passband Frequency
Fstop = 530;         % Stopband Frequency
Apass = 1;           % Passband Ripple (dB)
Astop = 80;          % Stopband Attenuation (dB)
match = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fsamp);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
