function Hd = bandpass( Fsamp )
%BANDPASS Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.11 and the Signal Processing Toolbox 6.14.
%
% Generated on: 17-May-2011 21:52:47
%

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 44100;  % Sampling Frequency

N    = 64;       % Order
Fc1  = 7700;     % First Cutoff Frequency
Fc2  = 14900;    % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fsamp/2), 'bandpass', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
