function Hd = lowpass( Fsamp )
%LOWPASS Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.11 and the Signal Processing Toolbox 6.14.
%
% Generated on: 17-May-2011 20:28:53
%

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
if nargin < 1       % If there is no input arguments
    Fsamp = 44100;  % Sampling Frequency
end

N    = 64;       % Order
Fc   = 502;      % Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = blackman(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fsamp/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
